version: "3"

services:
  nodejs:
    user: "root"
    working_dir: /home/node/app
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    ports:
      - "9000:9000"
    entrypoint: "./container_bin/start.sh"

  redis:
    image: redis
